"""added enabled/disabled db column

Revision ID: 64755dc173e8
Revises: b8a74c13ee97
Create Date: 2020-06-17 22:34:12.850351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64755dc173e8'
down_revision = 'b8a74c13ee97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_configs', sa.Column('accept_follow_requests_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('excluding_friends_friends_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('follow_and_interact_user_followers_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('follow_by_locations_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('follow_by_tags_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('follow_likers_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('follow_user_followers_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('follow_user_following_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('ignoring_users_friends_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('like_by_feed_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('like_by_locations_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('remove_follow_requests_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('restricting_likes_keywords_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('skip_users_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('unfollow_instapy_users_enabled', sa.Boolean(), nullable=False))
    op.add_column('instagram_configs', sa.Column('unfollow_users_who_dont_follow_back_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_configs', 'unfollow_users_who_dont_follow_back_enabled')
    op.drop_column('instagram_configs', 'unfollow_instapy_users_enabled')
    op.drop_column('instagram_configs', 'skip_users_enabled')
    op.drop_column('instagram_configs', 'restricting_likes_keywords_enabled')
    op.drop_column('instagram_configs', 'remove_follow_requests_enabled')
    op.drop_column('instagram_configs', 'like_by_locations_enabled')
    op.drop_column('instagram_configs', 'like_by_feed_enabled')
    op.drop_column('instagram_configs', 'ignoring_users_friends_enabled')
    op.drop_column('instagram_configs', 'follow_user_following_enabled')
    op.drop_column('instagram_configs', 'follow_user_followers_enabled')
    op.drop_column('instagram_configs', 'follow_likers_enabled')
    op.drop_column('instagram_configs', 'follow_by_tags_enabled')
    op.drop_column('instagram_configs', 'follow_by_locations_enabled')
    op.drop_column('instagram_configs', 'follow_and_interact_user_followers_enabled')
    op.drop_column('instagram_configs', 'excluding_friends_friends_enabled')
    op.drop_column('instagram_configs', 'accept_follow_requests_enabled')
    # ### end Alembic commands ###
