"""instagram settings

Revision ID: b8a74c13ee97
Revises: 730aa1922257
Create Date: 2020-06-16 22:26:29.187842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a74c13ee97'
down_revision = '730aa1922257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like_by_tags_enabled', sa.Boolean(), nullable=False),
    sa.Column('like_by_tags_tags', sa.String(length=1000), nullable=True),
    sa.Column('like_by_tags_amount', sa.Integer(), nullable=False),
    sa.Column('like_by_tags_skip_top_posts', sa.Boolean(), nullable=False),
    sa.Column('like_by_tags_randomize', sa.Boolean(), nullable=False),
    sa.Column('like_by_tags_media', sa.String(length=1000), nullable=True),
    sa.Column('like_by_tags_and_interact_enabled', sa.Boolean(), nullable=False),
    sa.Column('like_by_tags_and_interact_tags', sa.String(length=1000), nullable=True),
    sa.Column('like_by_tags_and_interact_like_amount', sa.Integer(), nullable=False),
    sa.Column('like_by_tags_and_interact_interact_amount', sa.Integer(), nullable=False),
    sa.Column('like_by_tags_and_interact_randomize', sa.Boolean(), nullable=False),
    sa.Column('like_by_tags_and_interact_percentage', sa.Integer(), nullable=False),
    sa.Column('like_by_tags_and_interact_media', sa.String(length=50), nullable=False),
    sa.Column('like_by_feed_amount', sa.Integer(), nullable=False),
    sa.Column('like_by_feed_randomize', sa.Boolean(), nullable=False),
    sa.Column('like_by_feed_unfollow', sa.Boolean(), nullable=False),
    sa.Column('like_by_feed_interact', sa.Boolean(), nullable=False),
    sa.Column('like_by_locations_locations', sa.String(length=1000), nullable=False),
    sa.Column('like_by_locations_amount', sa.Integer(), nullable=False),
    sa.Column('like_by_locations_skip_to_posts', sa.Boolean(), nullable=False),
    sa.Column('follow_by_tags_tags', sa.String(length=1000), nullable=False),
    sa.Column('follow_by_tags_amount', sa.Integer(), nullable=False),
    sa.Column('follow_by_tags_skip_top_posts', sa.Boolean(), nullable=False),
    sa.Column('follow_by_tags_randomize', sa.Boolean(), nullable=False),
    sa.Column('follow_by_tags_media', sa.String(length=50), nullable=False),
    sa.Column('follow_by_locations_locations', sa.String(length=1000), nullable=False),
    sa.Column('follow_by_locations_amount', sa.Integer(), nullable=False),
    sa.Column('follow_by_locations_skip_to_posts', sa.Boolean(), nullable=False),
    sa.Column('follow_user_followers_users', sa.String(length=1000), nullable=False),
    sa.Column('follow_user_followers_amount', sa.Integer(), nullable=False),
    sa.Column('follow_user_followers_randomize', sa.Boolean(), nullable=False),
    sa.Column('follow_user_following_users', sa.String(length=1000), nullable=False),
    sa.Column('follow_user_following_amount', sa.Integer(), nullable=False),
    sa.Column('follow_user_following_randomize', sa.Boolean(), nullable=False),
    sa.Column('follow_and_interact_user_followers_followers', sa.String(length=1000), nullable=False),
    sa.Column('follow_and_interact_user_followers_amount_interact', sa.Integer(), nullable=False),
    sa.Column('follow_and_interact_user_followers_randomize_interact', sa.Boolean(), nullable=False),
    sa.Column('follow_and_interact_user_followers_percentage', sa.Integer(), nullable=False),
    sa.Column('follow_and_interact_user_followers_media', sa.String(length=1000), nullable=False),
    sa.Column('follow_and_interact_user_followers_amount_followers', sa.Integer(), nullable=False),
    sa.Column('follow_and_interact_user_followers_randomize_followers', sa.Boolean(), nullable=False),
    sa.Column('follow_and_interact_user_followers_interact', sa.Boolean(), nullable=False),
    sa.Column('follow_likers_users', sa.String(length=1000), nullable=False),
    sa.Column('follow_likers_amount', sa.Integer(), nullable=False),
    sa.Column('follow_likers_percentage', sa.Integer(), nullable=False),
    sa.Column('follow_likers_randomize_interact', sa.Boolean(), nullable=False),
    sa.Column('follow_likers_media', sa.String(length=1000), nullable=False),
    sa.Column('follow_likers_photos_grab_amount', sa.Integer(), nullable=False),
    sa.Column('follow_likers_follow_likers_per_photo', sa.Integer(), nullable=False),
    sa.Column('follow_likers_randomize', sa.Boolean(), nullable=False),
    sa.Column('follow_likers_sleep_delay', sa.Integer(), nullable=False),
    sa.Column('follow_likers_interact', sa.Boolean(), nullable=False),
    sa.Column('unfollow_instapy_users_amount', sa.Integer(), nullable=False),
    sa.Column('unfollow_instapy_users_instapy_followed_enabled', sa.Boolean(), nullable=False),
    sa.Column('unfollow_instapy_users_instapy_followed_param', sa.String(length=1000), nullable=False),
    sa.Column('unfollow_instapy_users_style', sa.String(length=1000), nullable=False),
    sa.Column('unfollow_instapy_users_unfollow_after', sa.Integer(), nullable=False),
    sa.Column('unfollow_instapy_users_sleep_delay', sa.Integer(), nullable=False),
    sa.Column('unfollow_users_who_dont_follow_back_amount', sa.Integer(), nullable=False),
    sa.Column('unfollow_users_who_dont_follow_back_nonFollowers', sa.Boolean(), nullable=False),
    sa.Column('unfollow_users_who_dont_follow_back_style', sa.String(length=1000), nullable=False),
    sa.Column('unfollow_users_who_dont_follow_back_unfollow_after', sa.Integer(), nullable=False),
    sa.Column('unfollow_users_who_dont_follow_back_sleep_delay', sa.Integer(), nullable=False),
    sa.Column('accept_follow_requests_amount', sa.Integer(), nullable=False),
    sa.Column('accept_follow_requests_sleep_delay', sa.Integer(), nullable=False),
    sa.Column('remove_follow_requests_amount', sa.Integer(), nullable=False),
    sa.Column('remove_follow_requests_sleep_delay', sa.Integer(), nullable=False),
    sa.Column('skip_users_keywords', sa.String(length=2000), nullable=False),
    sa.Column('restricting_likes_keywords', sa.String(length=2000), nullable=False),
    sa.Column('ignoring_users_friends', sa.String(length=2000), nullable=False),
    sa.Column('excluding_friends_friends', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instagram_configs')
    # ### end Alembic commands ###
